# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0002_auto_20160923_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rec_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='logreg.Users')),
                ('send_poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='logreg.Users')),
            ],
        ),
    ]
